CREATE DATABASE IF NOT EXISTS DemoApi;

USE DemoApi;

CREATE TABLE IF NOT EXISTS User
(
	Id				INT 			NOT NULL 	UNIQUE AUTO_INCREMENT,
    Name 			VARCHAR(50) 	NOT NULL,
    Username 		VARCHAR(20) 	NOT NULL	UNIQUE,
    Password		VARCHAR(20) 	NOT NULL,
    Email 		 	VARCHAR(100) 	NOT NULL,
    Active 			TINYINT(1) 		NOT NULL,
    CreatedAt 		DATETIME 		NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS Role
(
	Id 				INT 			NOT NULL 	UNIQUE AUTO_INCREMENT,
    Name			VARCHAR(20) 	NOT NULL	UNIQUE,
	Description		VARCHAR(255) 	NULL,
    Active 			TINYINT(1) 		NOT NULL,
    CreatedAt 		DATETIME 		NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS UserRole
(
	Id				INT 			NOT NULL 	UNIQUE AUTO_INCREMENT,
	UserId			INT 			NOT NULL,
	RoleId			INT 			NOT NULL,
	PRIMARY KEY (Id),
	FOREIGN KEY (UserId) 			REFERENCES User(Id),
    FOREIGN KEY (RoleId) 			REFERENCES Role(Id)
);